@startuml

skinparam monochrome true
skinparam wrapWidth 300
skinparam defaultFontSize 12
skinparam defaultFontName Helvetica

' Definitions: sharp corners, plain background
skinparam rectangle<<part def>> {
    RoundCorner 0
    BackgroundColor white
    StereotypeFontSize 11
}
skinparam rectangle<<item def>> {
    RoundCorner 0
    BackgroundColor white
}
skinparam rectangle<<attribute def>> {
    RoundCorner 0
    BackgroundColor white
}
skinparam rectangle<<port def>> {
    RoundCorner 0
    BackgroundColor white
}
skinparam rectangle<<action def>> {
    RoundCorner 0
    BackgroundColor white
}
skinparam rectangle<<state def>> {
    RoundCorner 0
    BackgroundColor white
}
skinparam rectangle<<requirement def>> {
    RoundCorner 0
    BackgroundColor white
}
skinparam rectangle<<view def>> {
    RoundCorner 0
    BackgroundColor white
}
skinparam rectangle<<viewpoint def>> {
    RoundCorner 0
    BackgroundColor white
}
skinparam rectangle<<enumeration def>> {
    RoundCorner 0
    BackgroundColor white
}

' Usages: rounded corners, plain background
skinparam rectangle<<part>> {
    RoundCorner 15
    BackgroundColor white
}
skinparam rectangle<<item>> {
    RoundCorner 15
    BackgroundColor white
}
skinparam rectangle<<attribute>> {
    RoundCorner 15
    BackgroundColor white
}
skinparam rectangle<<port>> {
    RoundCorner 15
    BackgroundColor white
}
skinparam rectangle<<action>> {
    RoundCorner 15
    BackgroundColor white
}
skinparam rectangle<<state>> {
    RoundCorner 15
    BackgroundColor white
}
skinparam rectangle<<requirement>> {
    RoundCorner 15
    BackgroundColor white
}
skinparam rectangle<<view>> {
    RoundCorner 15
    BackgroundColor white
}
skinparam rectangle<<viewpoint>> {
    RoundCorner 15
    BackgroundColor white
}
skinparam rectangle<<enumeration>> {
    RoundCorner 15
    BackgroundColor white
}

' Views as folders
skinparam folder<<view def>> {
    BackgroundColor white
}
skinparam folder<<view>> {
    BackgroundColor white
}

top to bottom direction

title gv [model] 989ce4fa-42a3-4e75-808e-451de19d91ee

hide circle

rectangle "Wheel" as E1 <<part def>>
rectangle "radius" as E2 <<attribute>>
rectangle "pressure" as E4 <<attribute>>
rectangle "BrakeSystem" as E6 <<part def>>
rectangle "padThickness" as E7 <<attribute>>
rectangle "VehicleAssembly" as E9 <<part def>>
rectangle "frontLeft" as E10 <<part>>
rectangle "frontRight" as E11 <<part>>
rectangle "brakes" as E12 <<part>>
rectangle "myVehicle" as E13 <<part>>

E1 *-- E2
E1 *-- E4
E6 *-- E7
E9 *-- E10
E10 --:|> E1 : types
E9 *-- E11
E11 --:|> E1 : types
E9 *-- E12
E12 --:|> E6 : types
E13 --:|> E9 : types

legend right
  <b>SysML v2 Relationship Legend</b>
  Relationship: Notation
  Feature Typing: --:|>
  Specialization: --|>
  Redefinition: --||>
  Composite (owns): *--
  Shared: o--
  Binding: -[thickness=4]-
  Connector: -[thickness=2]->
  Flow: -->
  Dependency: ..>>
endlegend

@enduml