@startuml

skinparam monochrome true
skinparam wrapWidth 400
skinparam defaultFontSize 12
skinparam defaultFontName Helvetica

skinparam rectangle<<requirement def>> {
    RoundCorner 0
    BackgroundColor white
}
skinparam rectangle<<requirement>> {
    RoundCorner 15
    BackgroundColor white
}

top to bottom direction

title Requirement View

hide circle

rectangle "PerformanceRequirement" as E1 <<requirement def>>
rectangle "req1" as E2 <<requirement>>


legend right
  <b>Requirement View Legend</b>
  Relationship: Notation
  Satisfy: -->
  Verify: -->
  Derive: *--
  Refine: ..>>
  Composite (owns): *--
  Feature Typing: --:|> 
endlegend

@enduml