@startuml

skinparam monochrome true
skinparam wrapWidth 300
skinparam defaultFontSize 12
skinparam defaultFontName Helvetica

skinparam rectangle<<part def>> {
    RoundCorner 0
    BackgroundColor white
}
skinparam rectangle<<part>> {
    RoundCorner 15
    BackgroundColor white
}
skinparam rectangle<<port def>> {
    RoundCorner 0
    BackgroundColor white
}
skinparam rectangle<<port>> {
    RoundCorner 15
    BackgroundColor white
}
skinparam rectangle<<interface def>> {
    RoundCorner 0
    BackgroundColor white
}
skinparam rectangle<<interface>> {
    RoundCorner 15
    BackgroundColor white
}
skinparam rectangle<<item def>> {
    RoundCorner 0
    BackgroundColor white
}
skinparam rectangle<<item>> {
    RoundCorner 15
    BackgroundColor white
}
skinparam rectangle<<attribute def>> {
    RoundCorner 0
    BackgroundColor white
}
skinparam rectangle<<attribute>> {
    RoundCorner 15
    BackgroundColor white
}
skinparam rectangle<<connection def>> {
    RoundCorner 0
    BackgroundColor white
}
skinparam rectangle<<connection>> {
    RoundCorner 15
    BackgroundColor white
}
skinparam rectangle<<flow def>> {
    RoundCorner 0
    BackgroundColor white
}
skinparam rectangle<<flow>> {
    RoundCorner 15
    BackgroundColor white
}

top to bottom direction

title Interconnection View

hide circle

rectangle "Sensor" as E1 <<part def>>
rectangle "output" as E2 <<port>>
rectangle "Processor" as E3 <<part def>>
rectangle "input" as E4 <<port>>
rectangle "output" as E5 <<port>>
rectangle "Actuator" as E6 <<part def>>
rectangle "input" as E7 <<port>>
rectangle "Controller" as E8 <<part def>>
rectangle "s" as E9 <<part>>
rectangle "p" as E10 <<part>>
rectangle "a" as E11 <<part>>
rectangle "bed97ea3-b9f3-44c5-a104-5794d765c8ea" as E12 <<flow>>
rectangle "6388cf77-973b-4596-87a8-3f12a4583e54" as E13 <<flow>>

E1 *-- E2
E3 *-- E4
E3 *-- E5
E6 *-- E7
E8 *-- E9
E9 --:|> E1 : types
E8 *-- E10
E10 --:|> E3 : types
E8 *-- E11
E11 --:|> E6 : types
E8 *-- E12
E8 *-- E13


legend right
  <b>Interconnection Legend</b>
  |= Relationship |= Notation |
  | Binding | -[thickness=4]- |
  | Connector | -[thickness=2]-> |
  | Flow Transfer | --> |
  | Allocation | -[dotted]-> |
  | Feature Typing | --:|> |
  | Composite (owns) | *-- |
  | Specialization | --|> |
endlegend

@enduml