@startuml

skinparam monochrome true
skinparam wrapWidth 400
skinparam defaultFontSize 12
skinparam defaultFontName Helvetica

skinparam rectangle<<block>> {
    RoundCorner 0
    BackgroundColor white
    Padding 0
}

top to bottom direction

title Block Definition Diagram

hide circle

rectangle "Vehicle" as E1 <<block>> {
  attributes
    mass
    maxSpeed
  ports
    powerIn
  parts
    engine
}
rectangle "Engine" as E8 <<block>> {
  attributes
    horsepower
  ports
    powerOut
}


legend right
  <b>Block Definition Diagram Legend</b>
  |= Relationship |= Notation |
  | Generalization | --|> |
  | Composition | *-- |
  | Association | --> |
  | Attribute | (compartment) |
  | Port | (compartment) |
  | Part Reference | (compartment) |
endlegend

@enduml