@startuml

skinparam monochrome true
skinparam wrapWidth 300
skinparam defaultFontSize 12
skinparam defaultFontName Helvetica

skinparam rectangle<<constraint def>> {
    RoundCorner 0
    BackgroundColor white
    Padding 0
}
skinparam rectangle<<constraint>> {
    RoundCorner 10
    BackgroundColor #f8f8f8
}
skinparam rectangle<<parameter>> {
    RoundCorner 5
    BackgroundColor white
}

top to bottom direction

title Parametric Diagram

hide circle

rectangle "NewtonsLaw" as CD0 <<constraint def>> {
  rectangle "force: Real" as CD0_P0 <<parameter>>
  rectangle "mass: Real" as CD0_P1 <<parameter>>
  rectangle "acceleration: Real" as CD0_P2 <<parameter>>
}

rectangle "KineticEnergy" as CD1 <<constraint def>> {
  rectangle "energy: Real" as CD1_P0 <<parameter>>
  rectangle "mass: Real" as CD1_P1 <<parameter>>
  rectangle "velocity: Real" as CD1_P2 <<parameter>>
}



legend right
  <b>Parametric Diagram Legend</b>
  |= Element |= Notation |
  | Constraint Definition | rectangle with parameters |
  | Constraint Usage | rounded rectangle |
  | Parameter | small rectangle |
  | Binding | thick red line |
endlegend

@enduml