@startuml

skinparam monochrome true
skinparam wrapWidth 300
skinparam defaultFontSize 12
skinparam defaultFontName Helvetica

skinparam state<<state def>> {
    BackgroundColor white
    BorderColor black
}
skinparam state<<state>> {
    BackgroundColor white
    BorderColor black
}

top to bottom direction

title State Transition — Operational

hide circle

rectangle "Operational" as E1 <<state>>
rectangle "Idle" as E2 <<state>>
rectangle "Running" as E3 <<state>>
rectangle "Error" as E4 <<state>>

E1 --> E2
E1 --> E3
E1 --> E4


legend right
  <b>State Transition Legend</b>
  State Transition: thick green arrow
  Containment: simple arrow
endlegend

@enduml