@startuml

skinparam monochrome true
skinparam defaultFontSize 12
skinparam defaultFontName Helvetica
skinparam defaultFontName Monospaced

title Textual Notation

note as TextualNotation
part def Wheel
  attribute radius
  attribute pressure
part def BrakeSystem
  attribute padThickness
part def VehicleAssembly
  part frontLeft
  part frontRight
  part brakes
part myVehicle
end note

@enduml