@startuml

<style>
root {
    BackGroundColor white
    FontName Helvetica
    FontSize 13
}
rectangle {
    RoundCorner 15
    LineColor #444444
    LineThickness 1.5
    BackgroundColor white
    Padding 10
}
arrow {
    LineColor #555555
    LineThickness 1.5
    FontSize 11
}
</style>

skinparam wrapWidth 400

top to bottom direction

title SysML v2 — Vehicle

hide circle

rectangle "RotatingPart" as E1 <<(P,#32CD32) part def>>
rectangle "Wheel" as E2 <<(P,#32CD32) part def>>
rectangle "radius" as E3 <<(A,#32CD32) attribute>>
rectangle "mass" as E4 <<(A,#32CD32) attribute>>
rectangle "CarWheel" as E5 <<(P,#32CD32) part def>>
rectangle "2975dc91-a12e-409b-85ac-b944a97042fd" as E6 <<(A,#32CD32) attribute>>
rectangle "tirePressure" as E7 <<(A,#32CD32) attribute>>
rectangle "Engine" as E8 <<(P,#32CD32) part def>>
rectangle "horsepower" as E9 <<(A,#32CD32) attribute>>
rectangle "Transmission" as E10 <<(P,#32CD32) part def>>
rectangle "Axle" as E11 <<(P,#32CD32) part def>>
rectangle "Vehicle" as E12 <<(P,#32CD32) part def>>
rectangle "engine" as E13 <<(P,#32CD32) part>>
rectangle "transmission" as E14 <<(P,#32CD32) part>>
rectangle "frontLeft" as E15 <<(P,#32CD32) part>>
rectangle "frontRight" as E16 <<(P,#32CD32) part>>
rectangle "rearAxle" as E17 <<(P,#32CD32) part>>
rectangle "Truck" as E18 <<(P,#32CD32) part def>>
rectangle "bed" as E19 <<(P,#32CD32) part>>

E12 *-- E13
E13 -[dotted,thickness=1,#999999]:|> E8 : types
E12 *-- E14
E14 -[dotted,thickness=1,#999999]:|> E10 : types
E12 *-- E15
E15 -[dotted,thickness=1,#999999]:|> E5 : types
E12 *-- E16
E16 -[dotted,thickness=1,#999999]:|> E5 : types
E12 *-- E17
E17 -[dotted,thickness=1,#999999]:|> E11 : types

legend right
  <b>SysML v2 Relationship Legend</b>
  |= Relationship |= Notation |
  | Feature Typing | --:|> |
  | Specialization | --|> |
  | Redefinition | --||> |
  | Composite (owns) | *-- |
  | Shared | o-- |
  | Binding | -[thickness=4]- |
  | Connector | -[thickness=2]-> |
  | Flow | --> |
  | Dependency | ..>> |
endlegend

@enduml