@startuml

<style>
root {
    BackGroundColor white
    FontName Helvetica
    FontSize 13
}
rectangle {
    RoundCorner 15
    LineColor #444444
    LineThickness 1.5
    BackgroundColor white
    Padding 10
}
arrow {
    LineColor #555555
    LineThickness 1.5
    FontSize 11
}
</style>

skinparam wrapWidth 400

top to bottom direction

title 367529cd-db67-4c57-b2d7-294e5d100aaf

hide circle

rectangle "RotatingPart" as E1 <<(P,#32CD32) part def>>
rectangle "Wheel" as E2 <<(P,#32CD32) part def>>
rectangle "radius" as E3 <<(A,#32CD32) attribute>>
rectangle "mass" as E4 <<(A,#32CD32) attribute>>
rectangle "CarWheel" as E5 <<(P,#32CD32) part def>>
rectangle "2a2b446e-bbec-4a24-912b-497c0859318e" as E6 <<(A,#32CD32) attribute>>
rectangle "Vehicle" as E7 <<(P,#32CD32) part def>>
rectangle "frontLeft" as E8 <<(P,#32CD32) part>>

E2 --|> E1 : specializes
E2 *-- E3
E2 *-- E4
E5 --|> E2 : specializes
E5 *-- E6
E6 --||> E3 : redefines
E7 *-- E8
E8 --:|> E5 : types

legend right
  <b>SysML v2 Relationship Legend</b>
  |= Relationship |= Notation |
  | Feature Typing | --:|> |
  | Specialization | --|> |
  | Redefinition | --||> |
  | Composite (owns) | *-- |
  | Shared | o-- |
  | Binding | -[thickness=4]- |
  | Connector | -[thickness=2]-> |
  | Flow | --> |
  | Dependency | ..>> |
endlegend

@enduml