@startuml

skinparam monochrome true
skinparam wrapWidth 300
skinparam defaultFontSize 12
skinparam defaultFontName Helvetica

skinparam state<<state def>> {
    BackgroundColor white
    BorderColor black
}
skinparam state<<state>> {
    BackgroundColor white
    BorderColor black
}

top to bottom direction

title State Transition — Operational

hide circle

state "Operational" as E1 <<state def>>
state "Idle" as E2 <<state>>
state "Running" as E3 <<state>>
state "Error" as E4 <<state>>

E1 *-- E2
E1 *-- E3
E1 *-- E4


legend right
  <b>State Transition Legend</b>
  |= Relationship |= Notation |
  | Transition | --> |
  | Composite (owns) | *-- |
  | Feature Typing | --:|> |
endlegend

@enduml