@startuml

skinparam monochrome true
skinparam defaultFontSize 12
skinparam defaultFontName Helvetica

title Tabular View

 |= Name |= Type |= Kind |= Parent |= Typed By |= Specializes |= 
 | Wheel | part def | def | (root) |  |  | 
 | radius | attribute | usage | Wheel | Real |  | 
 | pressure | attribute | usage | Wheel | Real |  | 
 | BrakeSystem | part def | def | (root) |  |  | 
 | padThickness | attribute | usage | BrakeSystem | Real |  | 
 | VehicleAssembly | part def | def | (root) |  |  | 
 | frontLeft | part | usage | VehicleAssembly | Wheel |  | 
 | frontRight | part | usage | VehicleAssembly | Wheel |  | 
 | brakes | part | usage | VehicleAssembly | BrakeSystem |  | 
 | myVehicle | part | usage | (root) | VehicleAssembly |  | 

@enduml